apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewogICAgICAgICAgICAgImF1dGgiOiAiUmsxMWJHRnphR3RwYmpwbmFIQmZSV1JwWTJOdVVHOTVWbTlqV0ZCak0wNXBZa3RJZFhodVlXZzBWblIyTTA1WE5XVnUiCiAgICAgICAgfQogICAgfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0K
type: kubernetes.io/dockerconfigjson
